version: '3.8'

services:
  postgres:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_USER: dota2
      POSTGRES_PASSWORD: dota2password
      POSTGRES_DB: dota2db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dota2"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 